export { default as S_Home } from './Home'
export { default as S_Favorites } from './Favorites'
export { default as S_Products } from './Products'
export { default as S_ProductDetails } from './ProductDetails'
export { default as S_Checkout } from './Checkout'
export { default as S_AboutUs } from './AboutUs'
